-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Schema ventradas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ventradas` ;
use ventradas;
-- -----------------------------------------------------
-- Table `ventradas`.`band`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS genre (
genre VARCHAR(50) NOT NULL,
PRIMARY KEY (`genre`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS cities (
city VARCHAR(26) NULL
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `ventradas`.`band` (
  `idband` INT(11) NOT NULL AUTO_INCREMENT,
  `band_name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `components` VARCHAR(45) NULL DEFAULT NULL,
  `genre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idband`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ventradas`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventradas`.`user` (
  `iduser` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(15) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(80) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `favorite_band` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB

DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ventradas`.`concert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventradas`.`concert` (
  `id_concert` INT(11) NOT NULL AUTO_INCREMENT,
  `concert_name` VARCHAR(100) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `amount_tickets` INT(11) NULL DEFAULT NULL,
  `src` varchar(700) null,
  `date` date not null,
  `id_band` INT(11) NOT NULL,
  PRIMARY KEY (`id_concert`),
  INDEX `fk_concert_band_idx` (`id_concert` ASC),
  INDEX `fk_concert_band` (`id_band` ASC),
  CONSTRAINT `fk_concert_band`
    FOREIGN KEY (`id_band`)
    REFERENCES `ventradas`.`band` (`idband`))
  
ENGINE = InnoDB

DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ventradas`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventradas`.`tickets` (
  `idtickets` INT(11) NOT NULL AUTO_INCREMENT,
  `price` INT(11) NOT NULL,
  `band_id` INT(11) NOT NULL,
  PRIMARY KEY (`idtickets`),
  INDEX `fk_tickets_concert1_idx` (`band_id` ASC),
  CONSTRAINT `fk_tickets_concert1`
    FOREIGN KEY (`band_id`)
    REFERENCES `ventradas`.`concert` (`id_concert`))
ENGINE = InnoDB

DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ventradas`.`buy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventradas`.`buy` (
  `id_buy` INT(11) NOT NULL AUTO_INCREMENT,
  `user_iduser` INT(11) NOT NULL,
  `tickets_idtickets` INT(11)  not NULL,
  PRIMARY KEY (`id_buy`),
  INDEX `fk_buy_user1_idx` (`user_iduser` ASC),
  INDEX `fk_buy_tickets1_idx` (`tickets_idtickets` ASC),
  CONSTRAINT `fk_buy_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `ventradas`.`user` (`iduser`)
    ON UPDATE no action,
  CONSTRAINT `fk_buy_tickets1`
    FOREIGN KEY (`tickets_idtickets`)
    REFERENCES `ventradas`.`tickets` (`idtickets`)
    ON DELETE cASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (1, 'kbackshill0', 'Y0WVJsFJDP', 'Keen', 'Backshill', 'North Shore', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (2, 'hackenson1', 'Nhb55COBu', 'Herrick', 'Ackenson', 'Boston', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (3, 'ssauvan2', 'SLHyX4Ff', 'Shanan', 'Sauvan', 'Meishan', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (4, 'asprason3', 'KFJJoJC', 'Adria', 'Sprason', 'Gabahan', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (5, 'achoake4', 'w4U6rRC', 'Anderea', 'Choake', 'Changyŏn', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (6, 'bellwell5', 'mNSaSA', 'Berget', 'Ellwell', 'Cisiih', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (7, 'aguierre6', '71054Rlp', 'Aldus', 'Guierre', 'Sibulan', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (8, 'ehillan7', 'wnWGvHcuOpL', 'Elisa', 'Hillan', 'Xinpu', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (9, 'prisen8', '5hi1MXa4', 'Phyllida', 'Risen', 'Kamiichi', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (10, 'wbannerman9', 'SrMx3IGq3c', 'Wilton', 'Bannerman', 'Doudleby nad Orlicí', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (11, 'smidghalla', 'uAVbqvM9iZQ', 'Si', 'Midghall', 'Ueda', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (12, 'dlamploughb', 'ckHh74b', 'Doralynne', 'Lamplough', 'Yanyang', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (13, 'pbrookesc', 'MSizKpI', 'Petra', 'Brookes', 'San Isidro', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (14, 'csutterd', 'X1vUVFs', 'Collete', 'Sutter', 'Tafí del Valle', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (15, 'tczajkowskie', '8MRRyHtSghls', 'Tiffy', 'Czajkowski', 'Manutapen', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (16, 'mpregalf', 'IjncRq7Od8v7', 'Mathilda', 'Pregal', 'San Jose', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (17, 'hdymidowiczg', 'f2j48ccMj', 'Heddie', 'Dymidowicz', 'Gaocheng', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (18, 'gzorzih', 'siArtDu2hm', 'Giorgio', 'Zorzi', 'Bibai', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (19, 'pmacneillyi', 'Eege6T', 'Pennie', 'MacNeilly', 'Río', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (20, 'nblumj', '4FFQpNll', 'Niels', 'Blum', 'Potrerillos', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (21, 'ttatumk', 'f5CtcY', 'Torrance', 'Tatum', 'Sheki', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (22, 'jartisl', 'b94WhaYu', 'Jamesy', 'Artis', 'Zhuangbu', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (23, 'sbutlerm', 'pOYkRP', 'Selestina', 'Butler', 'Gornyye Klyuchi', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (24, 'kwaldockn', '2eDoFIU3m', 'Karissa', 'Waldock', 'Huiyi', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (25, 'bkaplano', 'i2HxlBK', 'Brittani', 'Kaplan', 'Opochka', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (26, 'mmantzp', '6ht5cv', 'Murray', 'Mantz', 'Gobernador Gálvez', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (27, 'emacanespieq', 'rviOnPV', 'Etti', 'MacAnespie', 'Morfovoúni', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (28, 'byesichevr', 'UA1CDT6R0L', 'Burlie', 'Yesichev', 'Arrabal', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (29, 'ktowerseys', 'Ll3WWzJKwy', 'Kara', 'Towersey', 'Kirkland Lake', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (30, 'cokellehert', '913JkdFAO', 'Claribel', 'O'' Kelleher', 'Landskrona', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (31, 'sbiswellu', 'kYLqUz5ktCku', 'Shaine', 'Biswell', 'Jacksonville', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (32, 'jorpinv', '0ruQDOHekCVN', 'Jeanna', 'Orpin', 'Al Ḩashwah', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (33, 'jpoulglaisw', 'iZqijyD6b', 'Jenn', 'Poulglais', 'Mvuma', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (34, 'fquaylex', 'wY2RlHuU', 'Fayre', 'Quayle', 'Vroutek', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (35, 'cebrally', 'NDRpBE', 'Caprice', 'Ebrall', 'Greensboro', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (36, 'mdahlborgz', 'POzggOvzYTEm', 'Maxie', 'Dahlborg', 'Mojorejo', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (37, 'dmallon10', 'JZiKQQpx8', 'Darline', 'Mallon', 'Ōmagari', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (38, 'mdickie11', 'pFGmY0xP', 'Misty', 'Dickie', 'El Coco', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (39, 'shultberg12', 'i9uOXctFOC', 'Spence', 'Hultberg', 'Chaumont', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (40, 'scouser13', 'x5EFO6', 'Shayne', 'Couser', 'Bungur', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (41, 'ddeclercq14', 'pxHxp65', 'Doy', 'de Clercq', 'Ramon Magsaysay', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (42, 'gcuddihy15', 'V86vXtl2cZ', 'Giffard', 'Cuddihy', 'Itō', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (43, 'jdulton16', 'Zd2XXBgU', 'Jennette', 'Dulton', 'Qinggis Han', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (44, 'sbeinisch17', 'B2Tbq19rMvy7', 'Sheridan', 'Beinisch', 'Pointe-à-Pitre', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (45, 'cdowner18', 'IpS3uVJ', 'Chandler', 'Downer', 'Pajak', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (46, 'dbray19', 'iPQhdqg6', 'Daryl', 'Bray', 'Surkhet', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (47, 'lsiddeley1a', 'L0cZBbrI654', 'Liliane', 'Siddeley', 'Napier', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (48, 'wlawther1b', '9sUxTmA', 'Waly', 'Lawther', 'Sorongan', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (49, 'ghadye1c', 'PxYFy32HapO', 'Gisela', 'Hadye', 'Muquiyauyo', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (50, 'aolland1d', '2aQsljNfzF', 'Adeline', 'Olland', 'Telangi Satu', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (51, 'jburrage1e', 'DP8YYL9SnLK1', 'Jedidiah', 'Burrage', 'Wichit', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (52, 'blandman1f', 'wKNy86gKI8C4', 'Bertie', 'Landman', 'Couto', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (53, 'ddecayette1g', 'Uun4na6q', 'Dacia', 'Decayette', 'Budapest', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (54, 'avashchenko1h', 'TmJGAvnq', 'Aurora', 'Vashchenko', 'San Clemente', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (55, 'mcaban1i', 'xWQTeYb6g3lK', 'Mariellen', 'Caban', 'Długosiodło', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (56, 'rvannuccinii1j', '2wlIqwbQxkfW', 'Roch', 'Vannuccinii', 'Nouméa', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (57, 'astoyle1k', 'grSZpY', 'Abbey', 'Stoyle', 'Brive-la-Gaillarde', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (58, 'abertelsen1l', '40Uzlh3zIxW', 'Augy', 'Bertelsen', 'Gaiyang', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (59, 'wmacneil1m', 'cNknqyz', 'Wally', 'MacNeil', 'General Pico', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (60, 'fkincla1n', 'Z2wdL7UK9F', 'Flory', 'Kincla', 'Cortes', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (61, 'dfilipychev1o', 'klD8sEeixda', 'Delmar', 'Filipychev', 'Cill Airne', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (62, 'dsquirrel1p', 'a16wmOQEw', 'Darin', 'Squirrel', 'Białołeka', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (63, 'tmanvell1q', 'Cp2rlGB2', 'Tristan', 'Manvell', 'Jintan', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (64, 'hwhapples1r', 'bCgdTTa', 'Hephzibah', 'Whapples', 'Turku', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (65, 'dlidgard1s', 'NdE5LUz9f', 'Dolly', 'Lidgard', 'Cairima', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (66, 'ngeorgiades1t', 'DnUAXECDNnA', 'Natalee', 'Georgiades', 'Lewotola', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (67, 'swreford1u', 'wzW1lfbAH02', 'Sallyann', 'Wreford', 'Mandalt', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (68, 'jcruickshanks1v', 'eq1h5RwN171', 'Janeczka', 'Cruickshanks', 'Timóteo', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (69, 'cbenduhn1w', 'Ia5eTBf', 'Clarie', 'Benduhn', 'Porto Salvo', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (70, 'ejolliffe1x', 'EtE3eUpv29', 'Eolande', 'Jolliffe', 'Jeremi', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (71, 'nsignorelli1y', 'osH485l', 'Nessie', 'Signorelli', 'Bačka Topola', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (72, 'kbastow1z', 'Nm0Hb035A', 'Karel', 'Bastow', 'Musawa', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (73, 'ahambelton20', '0yo2PvQLi', 'Alyce', 'Hambelton', 'Hněvotín', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (74, 'efairrie21', 'd7vwxcrSfGS', 'Erwin', 'Fairrie', 'Banjar Dauhpura', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (75, 'wbattany22', 'cn8jRPcLUh', 'Wilone', 'Battany', 'San Antonio de los Baños', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (76, 'hfearnsides23', 'nK159V5zp', 'Heddie', 'Fearnsides', 'Babo-Pangulo', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (77, 'mtiplady24', '7DNGjc', 'Miquela', 'Tiplady', 'Örebro', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (78, 'ccarlick25', 'KZ4SOa', 'Cornie', 'Carlick', 'Élancourt', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (79, 'jlardeur26', 'PUQTJ3Bk6', 'Jerald', 'Lardeur', 'Cungapmimbo', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (80, 'aibeson27', 'Lv02iQK', 'Anitra', 'Ibeson', 'Lyamino', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (81, 'ssartin28', 'RlH7E5B7px', 'Sidoney', 'Sartin', 'Homa Bay', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (82, 'dfitzmaurice29', '44iDBCo', 'Darrin', 'Fitzmaurice', 'Heshi', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (83, 'nharriskine2a', '2dJQqT42kDk', 'Nickolaus', 'Harriskine', 'Penanggapan', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (84, 'cgrinov2b', '5LmONXQ8', 'Claresta', 'Grinov', 'Wuli', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (85, 'tbrouard2c', 'KBUrwHNeCzp', 'Tallie', 'Brouard', 'Tullamore', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (86, 'eohannigan2d', 'dJr06b4N', 'Elysia', 'O''Hannigan', 'Berbérati', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (87, 'pmarl2e', 'NmhzHgOkAXx', 'Padgett', 'Marl', 'Velké Meziříčí', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (88, 'ldiangelo2f', 'oo5DogeGz', 'Lauri', 'Di Angelo', 'Anchorage', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (89, 'mleguin2g', 'Ai7ZDivYLk', 'Merle', 'Le Guin', 'Huajie', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (90, 'rderrett2h', 'hFTNn4E821', 'Royce', 'Derrett', 'Wangcheng', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (91, 'qhardiker2i', 'drcZG6ucD', 'Quinn', 'Hardiker', 'Strängnäs', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (92, 'lchisholm2j', 'NMFqieQRj3', 'Linus', 'Chisholm', 'Fomento', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (93, 'sshermar2k', 'pI80E3', 'Samantha', 'Shermar', 'Haysyn', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (94, 'wraddish2l', 'XSH40GWxi', 'Winonah', 'Raddish', 'Karano', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (95, 'kdockrill2m', 'JuGe6mVx3I9', 'Kristi', 'Dockrill', 'Pantenan', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (96, 'esedger2n', 'BkDqA0wBzU', 'Erin', 'Sedger', 'Albarraque', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (97, 'romoylan2o', 'YciLfimVNSZB', 'Reggi', 'O''Moylan', 'Dayong', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (98, 'mbendare2p', '10QpjH2', 'Mandy', 'Bendare', 'Nagosela', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (99, 'agimbart2q', 'jjCvE6F', 'Alain', 'Gimbart', 'Zebrzydowice', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (100, 'kaloway2r', 'hkqBZ9IUfauX', 'Kalinda', 'Aloway', 'Porto Martins', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (101, 'kdrover2s', 'EHi602wo', 'Kliment', 'Drover', 'Särö', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (102, 'gitzkovwitch2t', 'rkH6DrGnN', 'Geoffrey', 'Itzkovwitch', 'Šoštanj', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (103, 'dcavan2u', 'Z8fuSbaTXl', 'Donn', 'Cavan', 'Sambilawang', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (104, 'lbalmforth2v', 'H6nT6gZ5DUz', 'Lindsy', 'Balmforth', 'Thung Khru', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (105, 'aegger2w', 'axVrHo9', 'Angelita', 'Egger', 'Trzin', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (106, 'dstephen2x', '0ajya8kN5e', 'Desiri', 'Stephen', 'Sumeng', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (107, 'ajacobowits2y', 'WkR20n6DK8FB', 'Alfons', 'Jacobowits', 'Hudson Bay', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (108, 'escudder2z', 'ggLjqQAJjoM6', 'Elston', 'Scudder', 'Albergaria', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (109, 'aben30', 'oRGuDrx1pEa', 'Abby', 'Ben', 'Nice', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (110, 'vklageman31', 'dVfSJCfI', 'Vasilis', 'Klageman', 'Mādabā', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (111, 'bgillam32', 'fTTzkNH9i', 'Betteanne', 'Gillam', 'Kashirskoye', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (112, 'ematschuk33', 'kvyvzhO', 'Eileen', 'Matschuk', 'Granada', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (113, 'tdomenici34', 'U5RidgDtvn', 'Tony', 'Domenici', 'Bofuer', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (114, 'sbeagin35', '6D3ktlR', 'Sheree', 'Beagin', 'Koshki', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (115, 'goldfield36', 'y8DN7Rcd0', 'Geordie', 'Oldfield', 'Mogapinyana', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (116, 'mzelley37', 'HNTGALhb', 'Maryellen', 'Zelley', 'Jinyuan', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (117, 'hbursnoll38', 'LyIuzV2UrD', 'Heida', 'Bursnoll', 'Larnaca', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (118, 'saxworthy39', '8b3XTuUg5n', 'Shaylah', 'Axworthy', 'Jiahe', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (119, 'kaneley3a', 'HpzDggNBc', 'Kim', 'Aneley', 'Bofuer', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (120, 'ebagot3b', 'Xu3OM7Z17R', 'Elora', 'Bagot', 'Limbi', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (121, 'sthick3c', 'eP6S7VS', 'Selia', 'Thick', 'Sunne', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (122, 'nkelberman3d', 'bycEXTFc5F6', 'Nolie', 'Kelberman', 'Caucaguita', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (123, 'epountney3e', 'rC1mBzhn', 'Emlen', 'Pountney', 'Särevere', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (124, 'dfindlater3f', '7uqe7YxvZ94', 'Deena', 'Findlater', 'Gnosjö', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (125, 'bpollack3g', 'A3fL7AD9PMeI', 'Baird', 'Pollack', 'Masinloc', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (126, 'zelloway3h', 'kvHoPp', 'Zorine', 'Elloway', 'Tiksi', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (127, 'giwanczyk3i', 'Pltsnp2', 'Godfry', 'Iwanczyk', 'Krajan Langenharjo', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (128, 'jgettens3j', 'nqRABz69Mp', 'Jessa', 'Gettens', 'Ludwin', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (129, 'jgristwood3k', 'bjKSeUATFt7O', 'Janetta', 'Gristwood', 'Ban Phue', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (130, 'dplumbridge3l', 'OJgWgM', 'Denys', 'Plumbridge', 'Chitral', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (131, 'emoresby3m', 'Wd5Kqon', 'Erroll', 'Moresby', 'Pomacocha', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (132, 'dtollady3n', 'axYs6cy', 'Durward', 'Tollady', 'Huanipaca', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (133, 'fgadie3o', 'JnuZsxj63SLF', 'Freeman', 'Gadie', 'Twardogóra', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (134, 'tmeuse3p', 'FbhnEGa9', 'Truman', 'Meuse', 'Pompéia', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (135, 'cmartynov3q', 'HYCroV', 'Cordelia', 'Martynov', 'Purorejo', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (136, 'acamilli3r', 'fWb3mJy1', 'Anders', 'Camilli', 'Illushi', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (137, 'ilaverack3s', 'uClYodSdTF', 'Iain', 'Laverack', 'Alhos Vedros', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (138, 'ktowndrow3t', '7n8venq', 'Karisa', 'Towndrow', 'Hebian', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (139, 'avonnassau3u', 'yXFakbtrZE', 'Allan', 'von Nassau', 'Toulouse', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (140, 'bdolphin3v', 'NKH98VCWoN', 'Barret', 'Dolphin', 'Baicaogou', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (141, 'rhatfull3w', 'rD2C4BN8', 'Rockie', 'Hatfull', 'Mosteirô', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (142, 'lyukhin3x', 'ku4an2tC09', 'Liane', 'Yukhin', 'Uthai', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (143, 'bgossipin3y', 'GFI28Jhdr95F', 'Bibbye', 'Gossipin', 'Heba', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (144, 'vyuryev3z', 'uSFw80Owc', 'Vlad', 'Yuryev', 'Anh Son', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (145, 'cfuggles40', 'xmaanV', 'Catlaina', 'Fuggles', 'Nizhniy Lomov', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (146, 'pwhitloe41', 'SYWoUPadLynR', 'Peg', 'Whitloe', 'Selmes', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (147, 'sstallan42', 'pI5DbmzZZ', 'Sybyl', 'Stallan', 'Kalodu', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (148, 'ljilliss43', 'cYJxZRyQKsvf', 'Letta', 'Jilliss', 'Suru', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (149, 'eharvard44', 'udVIvmzh8E6', 'Emiline', 'Harvard', 'Skomielna Czarna', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (150, 'santuk45', 'Y3qZj3gGd4Wh', 'Sheilah', 'Antuk', 'Kirkton', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (151, 'nplet46', 'r7iAeP', 'Nissy', 'Plet', 'Lamas', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (152, 'dblondell47', 'm49YuPOMdYNN', 'Derek', 'Blondell', 'Swellendam', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (153, 'ndey48', 'LeihWYXLCp', 'Nicola', 'Dey', 'Jieduo', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (154, 'efownes49', '7FzdE5snSTm', 'Eunice', 'Fownes', 'Nueva Italia', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (155, 'fbaytrop4a', '6wm7JpCY', 'Felic', 'Baytrop', 'Boca Raton', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (156, 'cedelheit4b', 'gDtnTXS5lk', 'Cecilia', 'Edelheit', 'Gniechowice', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (157, 'cengledow4c', 'WAmiKeOE', 'Conni', 'Engledow', 'Águas', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (158, 'kstorie4d', '277ab21MnRp', 'Keelia', 'Storie', 'Kashihara-shi', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (159, 'dmcgaughey4e', 'Qk79lGx4trY', 'Drusy', 'McGaughey', 'København', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (160, 'zstringman4f', 'OIdJfkJvwqwp', 'Zelig', 'Stringman', 'Zhusha', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (161, 'yealles4g', 'vOMQhLOosN0U', 'Yule', 'Ealles', 'Sanligang', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (162, 'ktheyer4h', 'zsByDKf', 'Kelwin', 'Theyer', 'Mataguži', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (163, 'mwarland4i', 'HXTCzUrCV', 'Mathe', 'Warland', 'Mazeikiai', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (164, 'ngronw4j', 'CYGB3V4', 'Nevin', 'Gronw', 'Wakkanai', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (165, 'jelston4k', 'CYXbUXd2H', 'Jeri', 'Elston', 'Fangxi', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (166, 'abuddock4l', 'UlZgrouAs26', 'Alasteir', 'Buddock', 'Digos', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (167, 'cdavioud4m', 'OC2TYEpeNG', 'Clareta', 'Davioud', 'Podkumskiy', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (168, 'wfragino4n', 'ccxmKwbUVU', 'Wilone', 'Fragino', 'Colonias Unidas', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (169, 'hmacmeekan4o', '8HNKecqHkFZ', 'Hayden', 'MacMeekan', 'La Esperanza', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (170, 'fpaslow4p', '2zOEdU1p', 'Franchot', 'Paslow', 'Maimará', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (171, 'terratt4q', 'joUZX4XC', 'Towney', 'Erratt', 'Llipa', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (172, 'whabberjam4r', 'LCuZSUdWIO', 'Wallis', 'Habberjam', 'Fresno', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (173, 'mprettyman4s', '2a90pv', 'Moira', 'Prettyman', 'Siquirres', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (174, 'vbroinlich4t', '57nblSwK4TnJ', 'Vivienne', 'Broinlich', 'Feteira Pequena', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (175, 'cfritzer4u', 'AxKSOJLUU', 'Cairistiona', 'Fritzer', 'Czerwieńsk', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (176, 'dsedgemore4v', 'bR1ACe6R', 'Dare', 'Sedgemore', 'Kefar Yona', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (177, 'npeacher4w', 'En6yRED7', 'Niles', 'Peacher', 'Hedong', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (178, 'jroset4x', 'ZsJfuc', 'Joelly', 'Roset', 'Chenhu', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (179, 'anorthcote4y', 'At7FWmFJz91', 'Arty', 'Northcote', 'Bozhou', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (180, 'sbellson4z', 'ROfIfBx', 'Stevy', 'Bellson', 'Myrnyy', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (181, 'rkibel50', 'zjYvon', 'Royal', 'Kibel', 'Embalse', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (182, 'acumberledge51', 'lONzbJUwrlV', 'Anthony', 'Cumberledge', 'Roma', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (183, 'cdelacote52', 'kh4hFn', 'Cherry', 'Delacote', 'Dawa-Dawa', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (184, 'rwedon53', 'wBWofGexr', 'Ringo', 'Wedon', 'Siaton', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (185, 'thugo54', 'G16dkJE1MQ4r', 'Thekla', 'Hugo', 'Pariti', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (186, 'nrubberts55', 'A3CmvVNkfzV', 'Nesta', 'Rubberts', 'Arish', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (187, 'rvarndall56', 'Q8yxdl', 'Rodge', 'Varndall', 'Polzela', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (188, 'vcaslin57', 'Pp0nLMv', 'Vivienne', 'Caslin', 'Xiyuan', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (189, 'rrigglesford58', 'vapFaq', 'Robbie', 'Rigglesford', 'Tavira', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (190, 'ptownsley59', 'eA7m8XWl', 'Parrnell', 'Townsley', 'São Mateus do Maranhão', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (191, 'dchampion5a', 'x82nfIfchU', 'Deanna', 'Champion', 'Mawu', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (192, 'pbilsland5b', 'gXZu5y4UHg', 'Puff', 'Bilsland', 'Mwense', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (193, 'bskellorne5c', 'U7GPIK', 'Blancha', 'Skellorne', 'Buan', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (194, 'nbrunger5d', 'HAJD9nD4wb', 'Nerti', 'Brunger', 'Helsingborg', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (195, 'tcarnew5e', 'mfythUfdf', 'Torin', 'Carnew', 'Agenebode', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (196, 'ryarrow5f', 'tmnIT2EOdN', 'Roland', 'Yarrow', 'Ukhta', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (197, 'elestrange5g', 'IJ9VGcGaLM0', 'Esdras', 'Le Strange', 'Baishi', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (198, 'jmcgilvra5h', 'cBJ7XacY', 'Jarrad', 'McGilvra', 'Yangqiao', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (199, 'hbasli5i', 'ZFVbqA3ehg', 'Herculie', 'Bassilashvili', 'Smiřice', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (200, 'shalliburton5j', 'N6A5msLefe', 'Selestina', 'Halliburton', 'Hamilton', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (201, 'pcuthbertson5k', 'r7kD8W', 'Porty', 'Cuthbertson', 'Yuzui', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (202, 'glorente5l', 'YFKY2lRy', 'George', 'Lorente', 'Torino', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (203, 'cboddis5m', 'NkDLYDpHcu', 'Cecile', 'Boddis', 'Rongxing', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (204, 'adurand5n', 'Qs5kIXN8', 'Anallese', 'Durand', 'Samagaltay', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (205, 'pvell5o', 'aFzbxSc', 'Perceval', 'Vell', 'Luyang', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (206, 'tdrache5p', 'HRg1TlU', 'Tony', 'Drache', 'Ostroměř', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (207, 'nrosen5q', 'nfZtTXopc', 'Nedda', 'Rosen', 'Jonava', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (208, 'ihaddleston5r', 'Whq5WQtav', 'Ingeborg', 'Haddleston', 'Morteros', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (209, 'wchipp5s', 'z77xVVXMJ', 'Wylma', 'Chipp', 'Sasayama', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (210, 'sbutler5t', 'Ji6ZcU', 'Sharona', 'Butler', 'Tyresö', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (211, 'fdinse5u', '9C4CXpu', 'Filberte', 'Dinse', 'Hamm', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (212, 'rcuthbertson5v', 'tcmUp7tC5Z', 'Rosemarie', 'Cuthbertson', 'Lebedinovka', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (213, 'tcorwood5w', 'P6a0OQvJV', 'Tomaso', 'Corwood', 'Hetang', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (214, 'rwrack5x', 'L22BXCN191', 'Rolph', 'Wrack', 'Zhuhong', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (215, 'vnussey5y', 'zYbNXG06q', 'Vernen', 'Nussey', 'Dadianzi', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (216, 'lannand5z', '7MsiVqR', 'Loutitia', 'Annand', 'Dinaig', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (217, 'lspiteri60', 'P36zqKt', 'Lisabeth', 'Spiteri', 'Itacarambi', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (218, 'ogurner61', 'DlOgkex', 'Otto', 'Gurner', 'Ikeja', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (219, 'mmcrobert62', '9T695oVhgb', 'Marilee', 'McRobert', 'Askiz', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (220, 'dglaves63', 'zMuCRnT', 'Delmer', 'Glaves', 'Jawand', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (221, 'rtenniswood64', 'Lc1ohC', 'Raleigh', 'Tenniswood', 'Konduga', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (222, 'dpidon65', 'LiHhRdR', 'Dion', 'Pidon', 'Kumalarang', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (223, 'bcohalan66', 'BzeFtj8HlvD', 'Bobina', 'Cohalan', 'Santo Antônio do Amparo', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (224, 'chambleton67', '86G0Y9S', 'Charmaine', 'Hambleton', 'Tuamese', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (225, 'cretchless68', 'IN5k7y3', 'Carol', 'Retchless', 'Sebadelhe', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (226, 'smaccolm69', '1d0BzfAKej', 'Spike', 'MacColm', 'Kiangan', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (227, 'jmantrip6a', 'CQOsWRRBTmIl', 'Jacqueline', 'Mantrip', 'Räpina', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (228, 'mjerche6b', 'go6nETk', 'Monica', 'Jerche', 'Červené Pečky', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (229, 'ecutmere6c', 'a2ZnA3jW', 'Elbert', 'Cutmere', 'Sainyabuli', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (230, 'jhenighan6d', 'k49jMQHg', 'Jarred', 'Henighan', 'Sidi Moussa', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (231, 'aarnall6e', 'wLIkKCi', 'Ashlie', 'Arnall', 'Intipucá', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (232, 'jbrickstock6f', 'ZeZlPIOmKTil', 'Joni', 'Brickstock', 'Bardalah', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (233, 'tsommerton6g', 'dJ3bDF8', 'Tiphanie', 'Sommerton', 'Panalingaan', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (234, 'ajoinsey6h', 'uCAzxEO8A2r', 'Arabele', 'Joinsey', 'Tartu', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (235, 'gvandecastele6i', 'hn9s8FbMa', 'Gerry', 'Van de Castele', 'Tetyushi', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (236, 'dvink6j', 'orKP04IoLRM', 'Dolley', 'Vink', 'Banjar', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (237, 'nblacklawe6k', '8J0AILT', 'Ninnette', 'Blacklawe', 'Chenôve', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (238, 'skeeffe6l', 'mQuGyu', 'Skell', 'Keeffe', 'Tulay', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (239, 'aneathway6m', 'gAzcVrkvjk', 'Augy', 'Neathway', 'Salon-de-Provence', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (240, 'mmardy6n', 'M97KEIX', 'Marilyn', 'Mardy', 'Charlottenberg', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (241, 'rdanielot6o', 'f5TWj1egwxTU', 'Rudiger', 'Danielot', 'Marfino', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (242, 'lferentz6p', 'hgv2uwN', 'Lindy', 'Ferentz', 'La Unión', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (243, 'caldcorn6q', 'P3FO5Bq', 'Curr', 'Aldcorn', 'Dardhas', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (244, 'ppritchitt6r', 'zWOTQdsD', 'Phyllis', 'Pritchitt', 'Chojata', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (245, 'acapenor6s', 'mpuRE1P', 'Annamarie', 'Capenor', 'Compostela', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (246, 'lpitrasso6t', '519duf', 'Lanny', 'Pitrasso', 'Ibotirama', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (247, 'dflanigan6u', 'fRSBBiYOg', 'Dion', 'Flanigan', 'Coxim', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (248, 'plethbrig6v', 'c9Iwrv25C', 'Paul', 'Lethbrig', 'Myingyan', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (249, 'cvalerius6w', 'L1ElBDbg2wL', 'Candra', 'Valerius', 'Shangjia', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (250, 'ecarrivick6x', 'cVOqaYpLxA', 'Eula', 'Carrivick', 'Mamfe', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (251, 'kstanmore6y', 'EQpbjBw', 'Kaiser', 'Stanmore', 'Gunungmanik', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (252, 'tcoare6z', '7hCKjxbr', 'Tressa', 'Coare', 'Managua', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (253, 'tnattriss70', '8EGx9N8Mq3xE', 'Teena', 'Nattriss', 'Jaciara', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (254, 'bkillingback71', 'dkdGI0JXKDl', 'Burnaby', 'Killingback', 'Dushang', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (255, 'plesper72', '9ATeKmnS4C', 'Prinz', 'Lesper', 'Jianshe', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (256, 'atheunissen73', 'RCR4KjZ', 'Arther', 'Theunissen', 'Gaocang', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (257, 'telbourne74', 'UwWiUrF03sW8', 'Toinette', 'Elbourne', 'Jerada', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (258, 'lrouchy75', 'AFfs2SU', 'Leann', 'Rouchy', 'Torino', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (259, 'sbretherton76', 'uhz29b01dk', 'Sigrid', 'Bretherton', 'Fargo', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (260, 'tluty77', 'NJBI4TNiG9v', 'Timmie', 'Luty', 'Cowansville', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (261, 'kbarkus78', 'yzcNZ8lo', 'Karalee', 'Barkus', 'Batroûn', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (262, 'tpenas79', 'VhZe8kAC', 'Tabbi', 'Penas', 'Fenhe', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (263, 'sgoodhand7a', 'WBttyZt8LGTM', 'Stephi', 'Goodhand', 'Biguaçu', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (264, 'rcraw7b', '0cBFJqPCBIg', 'Rena', 'Craw', 'El Paso', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (265, 'ecoulsen7c', '1dOIjN', 'Ernest', 'Coulsen', 'Apaga', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (266, 'knoades7d', 'uNnyas', 'Kare', 'Noades', 'Quilo-quilo', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (267, 'rdepaepe7e', '4gdnlQ', 'Robbie', 'De Paepe', 'Thạnh Hóa', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (268, 'tfranscioni7f', 'ti1FYfv2Am2', 'Trixie', 'Franscioni', 'Lages', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (269, 'lbram7g', 'E1ugIK2lw', 'Laurent', 'Bram', 'Nowy Dwór Gdański', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (270, 'chawkes7h', 'eofx4ngx2T', 'Colas', 'Hawkes', 'Matinao', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (271, 'ljarritt7i', 'XYP5nPNs0q', 'Lyndy', 'Jarritt', 'Simpang', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (272, 'hshere7j', 'EfmwuC1ynC5v', 'Helge', 'Shere', 'Velikiye Borki', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (273, 'sshovel7k', 'NXp3SjNQEdQ', 'Sheila', 'Shovel', 'Hunkuyi', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (274, 'ltumilty7l', 'oBD1YP6', 'Lauretta', 'Tumilty', 'Cô Tô', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (275, 'kbreslin7m', 'xbTHcHVNo', 'Kaela', 'Breslin', 'Gomel', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (276, 'jjozsef7n', '4xtKqrYSW', 'Jilly', 'Jozsef', 'Nagu', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (277, 'ccabotto7o', 'NlpzYjSSw', 'Camala', 'Cabotto', 'Goubétto', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (278, 'pbeedle7p', 'dBrRedAB7', 'Piggy', 'Beedle', 'Sanhe', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (279, 'ehryskiewicz7q', 'OLsDYMNFhkx', 'Ewell', 'Hryskiewicz', 'Karagay', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (280, 'cbernardin7r', 'LhZA5d0', 'Clari', 'Bernardin', 'Weetombo', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (281, 'gtander7s', 'DbqHBMHZRp', 'Gael', 'Tander', 'Kikinda', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (282, 'jbolgar7t', 'WcotNdvQR', 'Jud', 'Bolgar', '‘Ayn al Bayḑā', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (283, 'rfleischmann7u', 'jJsmJrJGfXrj', 'Rebecca', 'Fleischmann', 'Tebingtinggi', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (284, 'lmatsell7v', 'YhdV759com', 'Laird', 'Matsell', 'Kärdla', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (285, 'zexell7w', '3n1cZPNAGU', 'Zelig', 'Exell', 'Värmdö', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (286, 'mrickerby7x', 'bNh1FPfr', 'Moyra', 'Rickerby', 'Kafr az Zayyāt', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (287, 'bsawart7y', 'FUfYdHdf7j', 'Broddie', 'Sawart', 'Komi', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (288, 'isprowell7z', 'Pxdgro5m0i', 'Irina', 'Sprowell', 'Dian-ay', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (289, 'mcoard80', '8pof5vi', 'Malvin', 'Coard', 'Cahuacho', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (290, 'fstothard81', '2f5mazsGuu90', 'Francisca', 'Stothard', 'Gandrungmangu', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (291, 'vpurrier82', 'UYYu7Y', 'Vivianna', 'Purrier', 'Huaquillas', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (292, 'hchilds83', 'YTh8ifuBqci3', 'Harcourt', 'Childs', 'Champaign', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (293, 'wspensley84', 'ltxnIY', 'Wood', 'Spensley', 'Mitrópoli', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (294, 'cmacquarrie85', 'tGx3ve', 'Celestyn', 'MacQuarrie', 'Lixu', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (295, 'rcorgenvin86', '8BOVMLKY5LwZ', 'Regan', 'Corgenvin', 'Erátyra', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (296, 'kfermer87', 'So43EXtfowL', 'Klaus', 'Fermer', 'Tyoply Stan', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (297, 'bkedge88', 'yrgfKn', 'Bondon', 'Kedge', 'Middelburg', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (298, 'cedmans89', 'UVtEbI3WDfo', 'Cori', 'Edmans', 'Tebingtinggi', false);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (299, 'nsolan8a', 'WMSKJxRzAnH9', 'Nessi', 'Solan', 'Akunk’', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (300, 'mstrainge8b', 'm1eUl7bR', 'Monika', 'Strainge', 'Puerto Santander', true);
insert into user (iduser, username, password, first_name, last_name, city, favorite_band) values (301, 'admin', 'admin', 'admin', 'admin', 'admin', 'admin');






INSERT INTO genre VALUES
("12-bar blues"),
("2 tone"),
("2-step garage"),
("4-beat"),
("50s progression"),
("a cappella"),
("accordion"),
("acid breaks"),
("acid house"),
("acid jazz"),
("acid rock"),
("acid techno"),
("acid trance"),
("acousmatic music"),
("acoustic"),
("adult contemporary"),
("african"),
("african blues"),
("african heavy metal"),
("african hip hop"),
("african-american"),
("afro cosmic disco"),
("afro-cuban jazz"),
("afrobeat"),
("afropop"),
("aggrotech"),
("aleatoric"),
("algerian"),
("alternative"),
("alternative country"),
("alternative dance"),
("alternative hip hop"),
("alternative metal"),
("alternative r&b"),
("alternative rock"),
("amami islands"),
("ambient"),
("ambient dub"),
("ambient house"),
("ambient music"),
("american folk revival"),
("americana"),
("anarchist"),
("anarcho punk"),
("anarcho-punk"),
("anasheed"),
("anatolian rock"),
("ancient"),
("anime"),
("anti-folk"),
("apala"),
("appalachian folk music"),
("arab pop"),
("arabic pop"),
("argentine rock"),
("ars antiqua"),
("ars nova"),
("ars subtilior"),
("art pop"),
("art punk"),
("art rock"),
("ashik"),
("asian"),
("asian american jazz"),
("asian underground"),
("assyrian pop music"),
("atlanta hip hop"),
("australian aboriginal"),
("australian country"),
("australian country music"),
("australian hip hop"),
("australian pub rock"),
("austropop"),
("avant-garde"),
("avant-garde jazz"),
("avant-garde metal"),
("avant-punk"),
("axé"),
("bachata"),
("background music"),
("baggy"),
("bahrain"),
("baila"),
("baisha xiyue"),
("baithak gana"),
("baião"),
("bajourou"),
("bakersfield sound"),
("bal-musette"),
("balakadri"),
("balearic beat"),
("balearic trance"),
("balinese gamelan"),
("balkan brass band"),
("ballad"),
("ballata"),
("ballet"),
("baltimore club"),
("bambuco"),
("banda"),
("bangsawan"),
("bantowbol"),
("barbadian"),
("barbershop"),
("barn dance"),
("baroque"),
("baroque pop"),
("basque"),
("bass"),
("bassline"),
("batucada"),
("batá-rumba"),
("baul"),
("beach"),
("beat"),
("beat music"),
("beatboxing"),
("beautiful"),
("beautiful music"),
("bebop"),
("beiguan"),
("bel canto"),
("belizean"),
("bend-skin"),
("benga"),
("bent edge"),
("berlin school"),
("bhajan"),
("bhangra"),
("bhangragga"),
("big band"),
("big beat"),
("big room"),
("biguine"),
("bihu"),
("bikutsi"),
("biomusic"),
("bitpop"),
("black metal"),
("black midi"),
("blackened death metal"),
("blue-eyed soul"),
("bluegrass"),
("blues"),
("blues ballad"),
("blues country"),
("blues rock"),
("blues shouter"),
("boi"),
("bolero"),
("bolivia"),
("bongo flava"),
("boogaloo"),
("boogie"),
("boogie-woogie"),
("bosnian"),
("bossa nova"),
("bounce"),
("bounce music"),
("bouncy house"),
("bouncy techno"),
("bouyon"),
("brass"),
("brazilian"),
("brazilian rock"),
("breakbeat"),
("breakbeat hardcore"),
("breakcore"),
("breakstep"),
("brega"),
("breton"),
("brick city club"),
("brill building"),
("brill building sound"),
("brit funk"),
("british"),
("british blues"),
("british dance band"),
("british folk revival"),
("british hip hop"),
("british invasion"),
("britpop"),
("broken beat"),
("brostep"),
("brown-eyed soul"),
("brukdown"),
("bubblegum dance"),
("bubblegum pop"),
("buddhist"),
("bulerías"),
("bullerengue"),
("bunraku"),
("burger-highlife"),
("burgundian school"),
("bush ballad"),
("byzantine"),
("c-pop"),
("ca din tulnic"),
("ca trù"),
("cabaret"),
("cadence rampa"),
("cadence-lypso"),
("cajun"),
("cajun fiddle tunes"),
("calinda"),
("calypso"),
("calypso-style baila"),
("campursari"),
("canadian blues"),
("canción"),
("candombe"),
("canon"),
("cantata"),
("cante chico"),
("cante jondo"),
("canterbury scene"),
("cantiga"),
("cantiñas"),
("canto livre"),
("cantopop"),
("canzone"),
("canzone napoletana"),
("cape jazz"),
("capoeira"),
("caribbean and caribbean-influenced"),
("cariso"),
("carnatic"),
("carol"),
("cartageneras"),
("cavacha"),
("celempungan"),
("cello rock"),
("celtic"),
("celtic fusion"),
("celtic hip hop"),
("celtic metal"),
("celtic music"),
("celtic punk"),
("celtic reggae"),
("celtic rock"),
("cha cha cha"),
("cha-cha-cha"),
("chacarera"),
("chakacha"),
("chalga"),
("chamamé"),
("chamber"),
("chamber jazz"),
("chamber music"),
("chamber pop"),
("champeta"),
("changüí"),
("chanson"),
("chant"),
("chanting"),
("chap hop"),
("charanga"),
("charanga-vallenata"),
("charikawi"),
("chastushka"),
("chicago blues"),
("chicago hip hop"),
("chicago house"),
("chicago soul"),
("chicano rap"),
("chicha"),
("chicken scratch"),
("children's music"),
("chill-out"),
("chillstep"),
("chillwave"),
("chimurenga"),
("chinese music"),
("chinese rock"),
("chiptune"),
("chopped and screwed"),
("choro"),
("chouval bwa"),
("chowtal"),
("christian alternative rock"),
("christian black metal"),
("christian country"),
("christian country music"),
("christian electronic"),
("christian hardcore"),
("christian hip hop"),
("christian metal"),
("christian music"),
("christian pop"),
("christian punk"),
("christian rock"),
("christian ska"),
("christmas carol"),
("christmas carols"),
("christmas music"),
("chumba"),
("church music"),
("chut-kai-pang"),
("chutney"),
("chutney soca"),
("chylandyk"),
("chèo"),
("chầu văn"),
("classic country"),
("classic female blues"),
("classical"),
("classical crossover"),
("classical music"),
("classical period"),
("close harmony"),
("coladeira"),
("coldwave"),
("combined rhythm"),
("comedy"),
("comedy music"),
("comedy rap"),
("comedy rock"),
("comic opera"),
("compas"),
("complextro"),
("concerto"),
("concerto grosso"),
("conga"),
("congolese rumba"),
("conjunto"),
("conscious hip hop"),
("contemporary christian music"),
("contemporary folk"),
("contemporary r&b"),
("continental jazz"),
("contradanza"),
("cool jazz"),
("coon song"),
("corrido"),
("country"),
("country blues"),
("country folk"),
("country music"),
("country pop"),
("country rap"),
("country rock"),
("country-rap"),
("coupé-décalé"),
("cowboy western music"),
("cowpunk"),
("creole"),
("cretan"),
("criolla"),
("crossover jazz"),
("crossover thrash"),
("crunk"),
("crunkcore"),
("crust punk"),
("crustgrind"),
("csárdás"),
("cuarteto"),
("cuban"),
("cueca"),
("cumbia"),
("cumbia rap"),
("cumbia villera"),
("cybergrind"),
("cải lương"),
("d-beat"),
("dabke"),
("dadra"),
("dadra tala"),
("daina"),
("dance"),
("dance music"),
("dance-pop"),
("dance-punk"),
("dance-rock"),
("dancehall"),
("dancehall music"),
("dangdut"),
("danger"),
("danish"),
("dansband"),
("dansband music"),
("danza"),
("danzón"),
("dappan koothu"),
("dark ambient"),
("dark cabaret"),
("dark electro"),
("dark pop"),
("dark rock"),
("dark wave"),
("darkcore"),
("darkcore jungle"),
("darkstep"),
("de dragote"),
("death"),
("death 'n' roll"),
("death industrial"),
("death metal"),
("death rock"),
("death-doom"),
("deathcore"),
("deathgrind"),
("deathrock"),
("deep funk"),
("deep house"),
("delta blues"),
("dementia"),
("descarga"),
("desert rock"),
("desi"),
("detroit blues"),
("detroit hip hop"),
("detroit techno"),
("dhamar"),
("dhrupad"),
("dhun"),
("digital hardcore"),
("dirge"),
("dirty rap"),
("disco"),
("disco polo"),
("diva house"),
("dixieland"),
("djent"),
("doina"),
("dondang sayang"),
("donegal fiddle tradition"),
("dongjing"),
("doo-wop"),
("doom metal"),
("doomcore"),
("downtempo"),
("dream pop"),
("dream trance"),
("drill"),
("drill and bass"),
("drill music"),
("drone"),
("drone metal"),
("drone music"),
("drum and bass"),
("drumstep"),
("dub"),
("dub techno"),
("dubstep"),
("dubstyle"),
("dubtronica"),
("dunedin sound"),
("dunun"),
("dutch house"),
("dutch jazz"),
("décima"),
("early"),
("east coast blues"),
("east coast hip hop"),
("easy listening"),
("electric blues"),
("electric folk"),
("electro"),
("electro backbeat"),
("electro house"),
("electro music"),
("electro swing"),
("electro-industrial"),
("electroacoustic"),
("electroacoustic music"),
("electroclash"),
("electronic"),
("electronic body music"),
("electronic dance"),
("electronic dance music"),
("electronic music"),
("electronic rock"),
("electronica"),
("electronicore"),
("electropop"),
("electropunk"),
("elevator music"),
("emo"),
("emo pop"),
("enka"),
("epic"),
("eremwu eu"),
("ethereal wave"),
("ethnic electronica"),
("ethno jazz"),
("euro disco"),
("euro house"),
("eurobeat"),
("eurodance"),
("european"),
("european classical"),
("european free jazz"),
("europop"),
("eurotrance"),
("exotica"),
("experimental"),
("experimental hip hop"),
("experimental music"),
("experimental pop"),
("experimental rock"),
("extreme metal"),
("fado"),
("falak"),
("fandango"),
("fann at-tanbura"),
("farruca"),
("fiddle"),
("fidget house"),
("fijiri"),
("filk"),
("filk music"),
("film"),
("film score"),
("filmi"),
("filmi-ghazal"),
("fingerstyle"),
("finnish"),
("flamenco"),
("florida breaks"),
("folk"),
("folk jazz"),
("folk metal"),
("folk music"),
("folk pop"),
("folk punk"),
("folk rock"),
("folktronica"),
("forró"),
("franco-country"),
("freak folk"),
("freakbeat"),
("free funk"),
("free improvisation"),
("free jazz"),
("free tekno"),
("freestyle"),
("freestyle music"),
("freestyle rap"),
("french caribbean"),
("french house"),
("french pop"),
("frevo"),
("fuji"),
("fuji music"),
("full on"),
("full on trance"),
("funaná"),
("funeral doom"),
("funk"),
("funk carioca"),
("funk metal"),
("funk rock"),
("funkadelic"),
("funkstep"),
("funktronica"),
("funky house"),
("furniture music"),
("fusion jazz"),
("future bass"),
("future garage"),
("future house"),
("futurepop"),
("g-funk"),
("gaana"),
("gabba"),
("gabber"),
("gagaku"),
("gaita zuliana"),
("galant"),
("game boy music"),
("gamelan"),
("gamelan bebonangan"),
("gamelan degung"),
("gamelan gong kebyar"),
("gamelan salendro"),
("gamelan selunding"),
("gamelan semar pegulingan"),
("gammaldans"),
("gandrung"),
("gangsta rap"),
("gangster rap"),
("gar"),
("garage house"),
("garage punk"),
("garage rock"),
("garba"),
("garifuna"),
("garifuna music"),
("gavotte"),
("gender wayang"),
("genge"),
("genoese"),
("german folk"),
("ghazal"),
("ghetto house"),
("ghettotech"),
("girl group"),
("glam metal"),
("glam punk"),
("glam rock"),
("glitch"),
("glitch hop"),
("gnawa"),
("go-go"),
("goa trance"),
("golden age hip hop"),
("gong chime"),
("goombay"),
("goregrind"),
("goshu ondo"),
("gospel"),
("gospel blues"),
("gothic metal"),
("gothic rock"),
("grebo"),
("gregorian chant"),
("grime"),
("grindcore"),
("grindie"),
("groove metal"),
("group sounds"),
("grunge"),
("grupera"),
("guadeloupean"),
("guajira"),
("gumbe"),
("gunchei"),
("gunka"),
("guoyue"),
("gwo ka"),
("gwo ka moderne"),
("gypsy jazz"),
("gypsy punk"),
("habanera"),
("hakka"),
("halling"),
("hambo"),
("hamburger schule"),
("hammond organ"),
("happy hardcore"),
("haqibah"),
("hard bop"),
("hard house"),
("hard nrg"),
("hard rock"),
("hard trance"),
("hardbag"),
("hardcore"),
("hardcore hip hop"),
("hardcore punk"),
("hardcore techno"),
("hardstep"),
("hardstyle"),
("harmonica blues"),
("hasapiko"),
("hawaiian"),
("heartland rock"),
("heavy metal"),
("hellbilly music"),
("hi-nrg"),
("highlife"),
("hill country blues"),
("hindustani"),
("hindustani classical"),
("hip hop"),
("hip hop music"),
("hip hop soul"),
("hip house"),
("hip pop"),
("hiplife"),
("hiragasy"),
("hokum"),
("hokum blues"),
("hong kong"),
("honky tonk"),
("honky-tonk"),
("honkyoku"),
("hora lungă"),
("hornpipe"),
("horror punk"),
("horrorcore"),
("house"),
("house music"),
("houston hip hop"),
("huayno"),
("hula"),
("humppa"),
("hunguhungu"),
("hyangak"),
("hymn"),
("hyphy"),
("hát tuồng"),
("icaro"),
("icelandic"),
("idm"),
("igbo"),
("igbo highlife"),
("igbo rap"),
("illbient"),
("impressionist"),
("improvisational"),
("incidental"),
("india"),
("indian classical music"),
("indian music"),
("indian pop"),
("indie"),
("indie folk"),
("indie pop"),
("indie rock"),
("indietronica"),
("indo jazz"),
("industrial"),
("industrial death metal"),
("industrial folk"),
("industrial hip hop"),
("industrial metal"),
("industrial music"),
("industrial musical"),
("industrial rock"),
("instrumental"),
("instrumental country"),
("instrumental hip hop"),
("instrumental rock"),
("intelligent dance"),
("inuit"),
("iranian pop"),
("irish"),
("irish folk"),
("irish rebel"),
("isicathamiya"),
("islamic music"),
("isolationism"),
("isolationist"),
("italo dance"),
("italo disco"),
("italo house"),
("izvorna bosanska"),
("j-pop"),
("j-rock"),
("jaipongan"),
("jam"),
("jamrieng samai"),
("jangle pop"),
("japanese"),
("japanoise"),
("jarana yucateca"),
("jarocho"),
("jawaiian"),
("jazz"),
("jazz blues"),
("jazz fusion"),
("jazz house"),
("jazz rap"),
("jazz rock"),
("jazz-funk"),
("jegog"),
("jenkka"),
("jerkin'"),
("jersey club"),
("jesus"),
("jig"),
("jing ping"),
("jingle"),
("jit"),
("jitterbug"),
("jive"),
("joged"),
("joged bumbung"),
("joik"),
("joropo"),
("jota"),
("jug"),
("juke joint blues"),
("jump blues"),
("jump-up"),
("jumpstyle"),
("jungle"),
("junkanoo"),
("jùjú"),
("k-pop"),
("kaba"),
("kabuki"),
("kacapi suling"),
("kachāshī"),
("kadongo kamu"),
("kagok"),
("kaiso"),
("kalamatianó"),
("kan ha diskan"),
("kansas city blues"),
("kansas city jazz"),
("kantrum"),
("kapuka"),
("kargyraa"),
("kaseko"),
("kawachi ondo"),
("kayōkyoku"),
("kecak"),
("kerala"),
("keroncong"),
("kertok"),
("khaleeji"),
("khaliji"),
("khene"),
("khoomei"),
("khyal"),
("kirtan"),
("kiwi rock"),
("kizomba"),
("klapa"),
("klasik"),
("klezmer"),
("kliningan"),
("kolomyjka"),
("komagaku"),
("korea"),
("korean"),
("kpanlogo"),
("kpop"),
("krakowiak"),
("krautrock"),
("kriti"),
("kroncong"),
("kuduro"),
("kulintang"),
("kundiman"),
("kuwait"),
("kvæði"),
("kwaito"),
("kwassa kwassa"),
("kwela"),
("lambada"),
("laptronica"),
("latin"),
("latin alternative"),
("latin american"),
("latin ballad"),
("latin christian"),
("latin house"),
("latin jazz"),
("latin metal"),
("latin music"),
("latin pop"),
("latin rock"),
("latin swing"),
("lavani"),
("laïkó"),
("legényes"),
("lento violento"),
("letkajenkka"),
("lhamo"),
("lied"),
("light"),
("liquid dubstep"),
("liquid funk"),
("liquindi"),
("livetronica"),
("liwa"),
("lo-fi"),
("logobi"),
("long song"),
("louisiana blues"),
("louisiana swamp pop"),
("louisianan"),
("lounge"),
("lounge music"),
("lovers rock"),
("low bap"),
("lowercase"),
("lu"),
("lubbock sound"),
("luk krung"),
("luk thung"),
("lullaby"),
("lundu"),
("lust"),
("lyrical hip hop"),
("m-base"),
("madchester"),
("madrigal"),
("mafioso rap"),
("mahori"),
("mainstream jazz"),
("makossa"),
("malacca"),
("malaysia"),
("malaysian"),
("malhun"),
("maloya"),
("mambo"),
("manaschi"),
("mandarin"),
("mandopop"),
("manele"),
("mangue bit"),
("manila sound"),
("mapouka"),
("marabi"),
("maracatu"),
("marathi"),
("mariachi"),
("marinera"),
("marrabenta"),
("martial industrial"),
("martinetes"),
("maskanda"),
("mass"),
("matamuerte"),
("math rock"),
("mathcore"),
("maxixe"),
("mazurka"),
("mbalax"),
("mbaqanga"),
("mbube"),
("medieval"),
("medieval folk rock"),
("medieval metal"),
("meditation"),
("meiji restoration"),
("mejoranera"),
("melam"),
("melbourne bounce"),
("melodic"),
("melodic death metal"),
("melodic hardcore"),
("melodic metalcore"),
("memphis blues"),
("memphis soul"),
("mento"),
("merengue"),
("merengue típico"),
("merenrap"),
("metal"),
("metalcore"),
("mexican pop"),
("mexican rock"),
("mexican son"),
("meykhana"),
("mezwed"),
("miami bass"),
("microhouse"),
("middle ages"),
("middle eastern music"),
("middle of the road"),
("midwest hip hop"),
("milonga"),
("min'yō"),
("minangkabau"),
("mini-jazz"),
("minimal"),
("minimal techno"),
("minimal trance"),
("minimal wave"),
("minneapolis sound"),
("minstrel"),
("minuet"),
("mississippi delta"),
("modal jazz"),
("modern classical"),
("modern laïka"),
("modern rock"),
("modinha"),
("montuno"),
("moombahcore"),
("moombahton"),
("mor lam"),
("mor lam sing"),
("morlam"),
("morna"),
("mosambique"),
("motown"),
("motswako"),
("mozambique"),
("mozambique of america"),
("mozambique of cuba"),
("mugham"),
("murga"),
("musette"),
("mushroom jazz"),
("music"),
("music drama"),
("music hall"),
("musica llanero"),
("musical improvisation"),
("musiqi-e assil"),
("musique concrète"),
("muwashshah"),
("mákina"),
("méringue"),
("música criolla"),
("música popular brasileira"),
("música sertaneja"),
("nagauta"),
("nagoya kei"),
("nakasi"),
("nangma"),
("nanguan music"),
("narcocorrido"),
("nardcore"),
("narodna muzika"),
("nashville sound"),
("national socialist black metal"),
("native american music"),
("ndombolo"),
("neapolitan"),
("nederpop"),
("neo kyma"),
("neo soul"),
("neo-bop jazz"),
("neo-classical metal"),
("neo-medieval"),
("neo-progressive rock"),
("neo-psychedelia"),
("neo-swing"),
("neoclassical"),
("neoclassical dark wave"),
("neoclassical metal"),
("neoclassical new age"),
("neofolk"),
("neotraditional country"),
("nepalese"),
("nerdcore"),
("neue deutsche härte"),
("neue deutsche todeskunst"),
("neue deutsche welle"),
("neurofunk"),
("neurohop"),
("new beat"),
("new jack swing"),
("new jersey hip hop"),
("new orleans blues"),
("new prog"),
("new rave"),
("new romanticism"),
("new school hip hop"),
("new taiwanese song"),
("new wave"),
("new wave of new wave"),
("new weird america"),
("new york blues"),
("new york city"),
("new-age"),
("new-age music"),
("nintendocore"),
("nisiotika"),
("nitzhonot"),
("no wave"),
("noh"),
("noise"),
("noise pop"),
("noise rock"),
("noisegrind"),
("nordic folk"),
("nordic folk dance"),
("nortec"),
("norteño"),
("northern soul"),
("novelty ragtime"),
("nu gaze"),
("nu jazz"),
("nu metal"),
("nu skool breaks"),
("nu-disco"),
("nu-funk"),
("nu-gaze"),
("nu-nrg"),
("nueva canción"),
("obscuro"),
("ocean grunge"),
("oi!"),
("old school hip hop"),
("old time radio"),
("old-time"),
("oldies"),
("olonkho"),
("ondo"),
("opera"),
("operatic pop"),
("operetta"),
("oratorio"),
("orchestra"),
("orchestral jazz"),
("orchestras"),
("organ trio"),
("organic ambient"),
("organum"),
("oriental metal"),
("original pilipino music"),
("ottava rima"),
("ottoman military band"),
("outlaw country"),
("outsider house"),
("outsider music"),
("p-funk"),
("pagan metal"),
("pagan rock"),
("pagode"),
("paisley underground"),
("palm wine"),
("palm-wine"),
("pambiche"),
("panambih"),
("panchai baja"),
("panchavadyam"),
("pansori"),
("paranda"),
("parang"),
("parliament"),
("parody"),
("parranda"),
("partido alto"),
("pasillo"),
("patriotic"),
("pbr&b"),
("peace punk"),
("pelimanni music"),
("pennsylvania"),
("persian traditional music"),
("peruvian cumbia"),
("petenera"),
("peyote song"),
("philadelphia"),
("philadelphia soul"),
("philippines"),
("piano blues"),
("piedmont blues"),
("pimba"),
("pinoy pop"),
("pinoy rock"),
("pinpeat orchestra"),
("piphat"),
("pirate metal"),
("piyyutim"),
("plainchant"),
("plena"),
("pleng phua cheewit"),
("pleng thai sakorn"),
("political hip hop"),
("polka"),
("polo"),
("polonaise"),
("pols"),
("polska"),
("polyphonic"),
("pong lang"),
("pop"),
("pop folk"),
("pop music"),
("pop punk"),
("pop rap"),
("pop rock"),
("pop soul"),
("pop sunda"),
("popera"),
("popular"),
("pornocore"),
("porro"),
("post-bop"),
("post-britpop"),
("post-disco"),
("post-dubstep"),
("post-grunge"),
("post-hardcore"),
("post-industrial"),
("post-metal"),
("post-minimalism"),
("post-punk"),
("post-punk revival"),
("post-rock"),
("post-romanticism"),
("pow-wow"),
("powada"),
("power duo"),
("power electronics"),
("power metal"),
("power noise"),
("power pop"),
("power trio"),
("powerviolence"),
("ppongtchak"),
("praise song"),
("program symphony"),
("progressive"),
("progressive bluegrass"),
("progressive country"),
("progressive electronic music"),
("progressive folk"),
("progressive folk music"),
("progressive house"),
("progressive metal"),
("progressive pop"),
("progressive rock"),
("progressive trance"),
("protest song"),
("protopunk"),
("psybient"),
("psychedelia"),
("psychedelic"),
("psychedelic folk"),
("psychedelic music"),
("psychedelic pop"),
("psychedelic rock"),
("psychedelic trance"),
("psychobilly"),
("psychobilly punkabilly"),
("pub rock (australia)"),
("pub rock (united kingdom)"),
("puerto rican"),
("pungmul"),
("punk"),
("punk blues"),
("punk cabaret"),
("punk jazz"),
("punk rock"),
("punta"),
("punta rock"),
("qasidah"),
("qasidah modern"),
("qawwali"),
("quadrille"),
("quan ho"),
("queercore"),
("quiet storm"),
("r&b"),
("r&b and soul"),
("raga"),
("raga rock"),
("ragga"),
("ragga jungle"),
("raggacore"),
("raggamuffin"),
("ragini"),
("ragtime"),
("raicore"),
("rake-and-scrape"),
("ramkbach"),
("ramvong"),
("ranchera"),
("rap"),
("rap metal"),
("rap music"),
("rap opera"),
("rap rock"),
("rapcore"),
("rapso"),
("rara"),
("rara tech"),
("rare groove"),
("rasin"),
("rasiya"),
("ravana"),
("ravanahatha"),
("rave"),
("raï"),
("raï'n'b"),
("reactionary bluegrass"),
("rebetiko"),
("red dirt"),
("red dirt (music)"),
("red river delta"),
("reel"),
("reggae"),
("reggae español spanish reggae"),
("reggae fusion"),
("reggae highlife"),
("reggaestep"),
("reggaeton"),
("regional mexican"),
("rekilaulu"),
("religious"),
("religious music"),
("rembetiko"),
("renaissance music"),
("requiem"),
("retro"),
("rhapsody"),
("rhumba"),
("rhyming spiritual"),
("rhythm and blues"),
("ricercar"),
("rio de janeiro"),
("riot grrrl"),
("rock"),
("rock and roll"),
("rock en español"),
("rock in opposition"),
("rock music"),
("rock opera"),
("rockabilly"),
("rocksteady"),
("rococo"),
("romantic period in music"),
("ronggeng"),
("roots reggae"),
("roots rock"),
("roots rock reggae"),
("rumba"),
("russian pop"),
("rímur"),
("sabar"),
("sacred harp"),
("sadcore"),
("saibara"),
("sakara"),
("salegy"),
("salsa"),
("salsa erotica"),
("salsa music"),
("salsa romantica"),
("saltarello"),
("samba"),
("samba rock"),
("samba-canção"),
("samba-reggae"),
("samba-rock"),
("sambai"),
("sambass"),
("sanjo"),
("sardana"),
("sato kagura"),
("sawt"),
("saya"),
("schlager"),
("schottisch"),
("scottish"),
("scottish baroque music"),
("screamo"),
("scrumpy and western"),
("scuff"),
("sea shanty"),
("sean nós"),
("seapunk"),
("second viennese school"),
("sega"),
("sega music"),
("seggae"),
("seis"),
("semba"),
("senegal"),
("sephardic music"),
("serialism"),
("sertanejo"),
("set dance"),
("sevdalinka"),
("sevillana"),
("shabad"),
("shalako"),
("shan'ge"),
("shangaan electro"),
("shango"),
("shape note"),
("shibuya-kei"),
("shidaiqu"),
("shima-uta"),
("shock rock"),
("shoegaze"),
("shoka"),
("shomyo"),
("show tune"),
("sica"),
("siguiriyas"),
("silat"),
("sinawi"),
("singer-songwriter"),
("ska"),
("ska jazz"),
("ska punk"),
("skald"),
("skate punk"),
("skiffle"),
("skullstep"),
("skweee"),
("slack-key guitar"),
("slide"),
("slowcore"),
("sludge metal"),
("slängpolska"),
("smooth jazz"),
("snap music"),
("soca"),
("soft rock"),
("son"),
("son cubano"),
("son montuno"),
("son-batá"),
("sonata"),
("songo"),
("songo-salsa"),
("sophisti-pop"),
("soukous"),
("soul"),
("soul blues"),
("soul jazz"),
("soul music"),
("soundtrack"),
("soundtracks"),
("south and southeast asian"),
("south india"),
("southern gospel"),
("southern harmony"),
("southern hip hop"),
("southern metal"),
("southern rock"),
("southern soul"),
("space age pop"),
("space disco"),
("space music"),
("space rock"),
("spanish"),
("spanish-speaking"),
("spectralism"),
("speed garage"),
("speed metal"),
("speedcore"),
("spirituals"),
("spouge"),
("sprechgesang"),
("square dance"),
("st. louis blues"),
("st. louis hip hop"),
("steelband"),
("stoner metal"),
("stoner rock"),
("straight edge"),
("straight-ahead jazz"),
("strathspeys"),
("street bass"),
("street punk"),
("stride"),
("stride jazz"),
("string"),
("string quartet"),
("sufi"),
("sufi music"),
("sufi rock"),
("suite"),
("sundanese"),
("sung poetry"),
("sunshine pop"),
("suomirock"),
("suomisaundi"),
("super eurobeat"),
("surf ballads"),
("surf instrumental"),
("surf music"),
("surf pop"),
("surf rock"),
("swamp blues"),
("swamp pop"),
("swamp rock"),
("swing"),
("swing music"),
("swiss"),
("sygyt"),
("symphonic black metal"),
("symphonic metal"),
("symphonic poem"),
("symphonic rock"),
("symphony"),
("synthpop"),
("synthwave"),
("synthwave (1980s genre)"),
("synthwave (2000s genre)"),
("t'ong guitar"),
("taarab"),
("tagalog"),
("tai tu"),
("taiwanese"),
("taiwanese pop"),
("tala"),
("talempong"),
("talking blues"),
("tambu"),
("tamburitza"),
("tamil christian keerthanai"),
("tango"),
("tanguk"),
("tappa"),
("taqwacore"),
("tarana"),
("tarantella"),
("taranto"),
("tech house"),
("tech trance"),
("techdombe"),
("technical death metal"),
("technical metal"),
("techno"),
("technoid"),
("techstep"),
("techtonik"),
("tecno brega"),
("tecnobrega"),
("teen pop"),
("tejano"),
("tejano music"),
("tekno"),
("tembang sunda"),
("tempo"),
("texas blues"),
("texas country"),
("thai"),
("thai pop"),
("theme music"),
("thillana"),
("third stream"),
("third wave ska"),
("thirty-two-bar form"),
("thrash metal"),
("thrashcore"),
("thumri"),
("tibetan"),
("tibetan pop"),
("tientos"),
("timba"),
("timbila"),
("tin pan alley"),
("tinga"),
("tinku"),
("toeshey"),
("togaku"),
("tohono o'odham"),
("trad jazz"),
("traditional"),
("traditional country music"),
("traditional pop music"),
("trallalero"),
("trance"),
("trance music"),
("trap"),
("trap music"),
("trapstep"),
("tribal house"),
("trikitixa"),
("trinidadian"),
("trip hop"),
("trival"),
("tropical"),
("tropical house"),
("tropical music"),
("tropicalia"),
("tropipop"),
("truck-driving country"),
("tumba"),
("turbo-folk"),
("turkish music"),
("turkish pop"),
("turntablism"),
("tuva throat singing"),
("tuvan throat singing"),
("tuvan throat-singing"),
("twee pop"),
("twin cities hip hop"),
("twist"),
("two tone"),
("twoubadou"),
("táncház"),
("uk funky"),
("uk garage"),
("uk hard house"),
("uk hardcore"),
("uk pub rock"),
("unblack metal"),
("underground hip hop"),
("underground music"),
("united states"),
("uplifting trance"),
("urban cowboy"),
("urban folk"),
("urban pasifika"),
("v-pop"),
("vallenato"),
("vaporwave"),
("vaudeville"),
("venezuelan"),
("verbunkos"),
("verismo"),
("video game music"),
("vietnamese"),
("viking metal"),
("villanella"),
("virelais"),
("vispop"),
("visual kei"),
("visual music"),
("vocal house"),
("vocal jazz"),
("vocal music"),
("vocal trance"),
("vocaloid"),
("volksmusik"),
("vomitstep"),
("waila"),
("waltz"),
("wangga"),
("war metal"),
("warabe uta"),
("wassoulou"),
("wedding"),
("were music"),
("west african"),
("west coast blues"),
("west coast hip hop"),
("west coast jazz"),
("west country"),
("western blues"),
("western swing"),
("westernmost"),
("whistling"),
("witch house"),
("wizard rock"),
("women's music"),
("wong shadow"),
("wonky"),
("wonky pop"),
("wood"),
("work song"),
("world fusion"),
("world music"),
("worldbeat"),
("xhosa music"),
("xoomii"),
("xote"),
("yakut"),
("yass"),
("yayue"),
("yo-pop"),
("yodeling"),
("youth crew"),
("yukar"),
("yé-yé"),
("zajal"),
("zamrock"),
("zapin"),
("zarzuela"),
("zef"),
("zeibekiko"),
("zeuhl"),
("ziglibithy"),
("zouglou"),
("zouk"),
("zouk-lambada"),
("zouklove"),
("zulu music"),
("zydeco"),
("čalgija");


INSERT INTO cities VALUES
("madrid"),
("barcelona"),
("sevilla"),
("bilbao"),
("valencia"),
("zaragoza"),
("malaga"),
("murcia"),
("granada"),
("vigo"),
("palma"),
("a Coruña"),
("santa maria de gracia"),
("gijon"),
("valladolid"),
("cordoba"),
("alicante"),
("cadiz"),
("pamplona"),
("oviedo"),
("zuazo de vitoria"),
("santander"),
("cartagena"),
("marbella"),
("mataro"),
("almeria"),
("burgos"),
("salamanca"),
("albacete"),
("huelva"),
("logroño"),
("badajoz"),
("leon"),
("tarragona"),
("ourense"),
("jaen"),
("Aageciras"),
("santiago de compostela"),
("lorca"),
("toledo"),
("guadalajara"),
("linares"),
("arrecife"),
("merida"),
("las Palmas de Gran Canaria"),
("vitoria-Gasteiz"),
("castellon de la Plana"),
("valencia"),
("lleida"),
("caceres"),
("segovia"),
("pontevedra"),
("santa cruz de tenerife"),
("soria"),
("huesca"),
("donostia"),
("cuenca"),
("girona"),
("avila"),
("ciudad real"),
("zamora"),
("lugo"),
("teruel");

insert into band VALUES(1,"Queen","La mejor banda de rock","","rock");

insert into band VALUES(2,"The Beatles","El más admirado y popular de la década de 1960","","rock");

insert into band VALUES(3,"Metallica","La mejor banda de metal","","Thrash metal");

insert into band Values(4,"Duki","El máximo exponente del trap argentino","Duki","trap");

insert into band Values(5,"Malú","Cantante de pop español","Malú","pop");


INSERT INTO `ventradas`.`concert` (`id_concert`, `concert_name`, `city`, `amount_tickets`, `src`, `date`, `id_band`) VALUES (1, 'God Save The Queen', 'Madrid', '200', 'https://i.imgur.com/BRSY8Dk.jpg', '2019-6-3', '1');
INSERT INTO `ventradas`.`concert` (`id_concert`, `concert_name`, `city`, `amount_tickets`, `src`, `date`, `id_band`) VALUES (2, 'Hijo de la noche', 'Barcelona', '50', 'https://i.imgur.com/b1PNdJ3.jpg', '2019-6-30', '4');
INSERT INTO `ventradas`.`concert` (`id_concert`, `concert_name`, `city`, `amount_tickets`, `src`, `date`, `id_band`) VALUES (3, 'Oxigeno tour', 'Sevilla', '200', 'https://i.imgur.com/SbBm9l9.png', '2019-5-23', '5');

insert into tickets values(1,"10","1");

insert into tickets values(2,"30","2");

insert into tickets values(3,"5","3");

